stages:
  - generate
  - validate
  - configure

before_script:
  - source /home/sudarshanv/ansible2.9.6/bin/activate

Generate the configuration:
  stage: generate
  script: 
    - ansible-playbook ansible-playbooks/generate_config.yaml -i ansible-playbooks/hosts.ini

Validate the configuration:
  stage: validate
  script:
    - ansible-playbook ansible-playbooks/batfish_test.yaml -i ansible-playbooks/hosts.ini

  