variables:
  GIT_CLONE_PATH: /home/gitlab-runner/builds/batfishpipeline

stages:
  - generate

cache:
  paths:
    - /home/gitlab-runner/ansible2.9.6

Generate the configuration:
  stage: generate
  script:
    - source /home/gitlab-runner/ansible2.9.6/bin/activate
    - ansible-playbook /home/gitlab-runner/builds/batfishpipeline/ansible-playbooks/generate_config.yaml 
      -i /home/gitlab-runner/builds/batfishpipeline/ansible-playbooks/hosts.ini
  