stages:
  - generate
  - validate
  - configure

before_script:
  - source /home/sudarshanv/ansible2.9.6/bin/activate

Generate the configuration:
  stage: generate
  script: 
    - ansible-playbook /var/lib/gitlab-runner/builds/rxauB3RV/0/root/ansible-batfish-cicd/ansible-playbooks/generate_config.yaml -i /var/lib/gitlab-runner/builds/rxauB3RV/0/root/ansible-batfish-cicd/ansible-playbooks/hosts.ini

Validate the configuration:
  stage: validate
  script:
    - ansible-playbook ansible-playbooks/batfish_test.yaml -i ansible-playbooks/hosts.ini

Configures the devices:
  stage: configure
  script:
    - ansible-playbook ansible-playbooks/configure_device.yaml -i ansible-playbooks/hosts.ini
  only: 
    - master