variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/cicd

stages:
  - generate
  - validate
  - configure

before_script:
  - source /home/sudarshan/ansible2.9/bin/activate

Generate the configuration:
  stage: generate
  script: 
    - mkdir snapshot
    - ansible-playbook ansible-playbooks/generate_config.yaml -i ansible-playbooks/hosts.ini
    - cp -R ansible-playbooks/snapshot/* snapshot
  artifacts:
    paths: 
      - snapshot
    expire_in: 3 day

Validate the configuration:
  stage: validate
  script:
    - cat /home/gitlab-runner/builds/cicd/snapshot/configs/Router1.cfg
    # - ansible-playbook ansible-playbooks/batfish_test.yaml -i ansible-playbooks/hosts.ini

# Configures the devices:
#   stage: configure
#   script:
#     - cat /home/gitlab-runner/builds/cicd/ansible-playbooks/snapshot/configs/Router1.cfg
#     - cat /home/gitlab-runner/builds/cicd/ansible-playbooks/snapshot/configs/Router2.cfg
#     - cat /home/gitlab-runner/builds/cicd/ansible-playbooks/snapshot/configs/Router3.cfg
#     - cat /home/gitlab-runner/builds/cicd/ansible-playbooks/snapshot/configs/Router4.cfg

  #   - ansible-playbook ansible-playbooks/configure_device.yaml -i ansible-playbooks/hosts.ini
  # only: 
  #   - master