variables:
  GIT_CLONE_PATH: /home/gitlab-runner/builds/batfishpipeline

stages:
  - generate

before_script:
  - source ~/ansible2.9.6/bin/activate

Generate the configuration:
  stage: generate
  script:
    - ansible-playbook /home/gitlab-runner/builds/batfishpipeline/ansible-playbooks/generate_config.yaml 
      -i /home/gitlab-runner/builds/batfishpipeline/ansible-playbooks/hosts.ini
  