hostname: Router2

interfaces:
  loopback2:
    ip_address: 2.2.2.2/32
    is_enable: True
  
  FastEthernet1/0:
    ip_address: 10.10.23.2/24
    is_enable: True

  FastEthernet2/0:
    ip_address: 10.10.12.2/24
    is_enable: True
    
bgp:
  asn: 65002
  neighbors:
    - neighbor_ipaddress: 10.10.12.1
      neighbor_asn: 65001
    - neighbor_ipaddress: 10.10.23.3
      neighbor_asn: 65003