hostname: Router2

interfaces:
  loopback2:
    ip_address: 2.2.2.2
    subnet_mask: 255.255.255.255
    is_enable: True

  FastEthernet0/0:
    ip_address: 192.168.1.192
    subnet_mask: 255.255.255.0
    is_enable: True
  
  FastEthernet1/0:
    ip_address: 10.10.23.2
    subnet_mask: 255.255.255.0
    is_enable: True

  FastEthernet2/0:
    ip_address: 10.10.12.2 
    subnet_mask: 255.255.255.0
    is_enable: True
    
ospf:
  process_id: 1
  router_id: 2.2.2.2
  area_id: 0
  interfaces:
    - FastEthernet1/0
    - FastEthernet2/0