---
- name: Configures devices with new configuration
  hosts: cisco
  gather_facts: False

  tasks:

    - name: ios config replace
      ios_config:
        src: /home/gitlab-runner/builds/cicd/snapshot/configs/{{ inventory_hostname }}.cfg
        save_when: changed
...

