---
- name: Configures devices with new configuration
  hosts: cisco
  gather_facts: False

  tasks:

    - name: ios config replace
      ios_config:
        src: snapshot/configs/{{inventory_hostname}}.cfg
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: /var/lib/gitlab-runner/builds/rxauB3RV/0/root/ansible-batfish-cicd/ansible-playbooks/backup
        save_when: changed
