# This playbook generates configuration based on variables mentioned in host_vars
# and the configuration.j2 jinja template in the templates folder.
# the generated configuration template is stored in snapshot/conifgs
---
  - name: Generate Router configuration files
    hosts: cisco
    gather_facts: false

    tasks:

      - name: Generate config from jinja
        template:
          src: /home/gitlab-runner/builds/cicd/ansible-playbooks/templates/configuration.j2
          dest: /home/gitlab-runner/builds/cicd/ansible-playbooks/snapshot/configs/{{ inventory_hostname }}.cfg
...