---
  - name: Generate Router configuration files
    hosts: cisco
    gather_facts: false

    tasks:

      - name: Generate config from jinja
        template:
          src: /home/gitlab-runner/builds/batfishpipeline/ansible-playbooks/templates/configuration.j2
          dest: /home/gitlab-runner/builds/batfishpipeline/ansible-playbooks/snapshot/configs/{{ inventory_hostname }}.cfg
        tags: hostname
