---
  - name: Generate Router configuration files
    hosts: cisco
    gather_facts: false

    tasks:

      - name: Generate config from jinja
        template:
          src: /var/lib/gitlab-runner/builds/rxauB3RV/0/root/ansible-batfish-cicd/ansible-playbooks/templates/configuration.j2
          dest: /var/lib/gitlab-runner/builds/rxauB3RV/0/root/ansible-batfish-cicd/snapshot/configs/{{ inventory_hostname }}.cfg
...